"""Lifecycle state transitions for application executor.

Lifecycle states and transition rules:
- UNAPPLIED -> APPLIED (on successful application)
- APPLIED is terminal (no further transitions)

Rejection precedence within lifecycle:
1. Invalid state -> LIFECYCLE_INELIGIBLE
2. Already applied -> ALREADY_APPLIED_ARTIFACT
"""

VALID_APPLICATION_STATES = frozenset(["UNAPPLIED", "APPLIED"])
VALID_LIFECYCLE_STATES = frozenset([
    "GRANTED_UNCONSUMED", "CONSUMED", "APPLIED",
    "REVOKED", "EXPIRED",
])

APPLICATION_ACCEPTED = "APPLICATION_ACCEPTED"
REJECTION_ARTIFACT_SCHEMA_INVALID = "ARTIFACT_SCHEMA_INVALID"
REJECTION_ARTIFACT_LIFECYCLE_NOT_UNAPPLIED = "ARTIFACT_LIFECYCLE_NOT_UNAPPLIED"
REJECTION_ARTIFACT_DIGEST_MISMATCH = "ARTIFACT_DIGEST_MISMATCH"
REJECTION_COMPILER_IDENTITY_MISMATCH = "COMPILER_IDENTITY_MISMATCH"
REJECTION_CAPABILITY_IDENTITY_MISMATCH = "CAPABILITY_IDENTITY_MISMATCH"
REJECTION_EXPECTED_STATE_DIGEST_MISMATCH = "EXPECTED_STATE_DIGEST_MISMATCH"
REJECTION_LIFECYCLE_INELIGIBLE = "LIFECYCLE_INELIGIBLE"
REJECTION_CONSUMER_IDENTITY_MISMATCH = "CONSUMER_IDENTITY_MISMATCH"
REJECTION_AUTHORITY_DOMAIN_VIOLATION = "AUTHORITY_DOMAIN_VIOLATION"
REJECTION_SCOPE_MISMATCH = "SCOPE_MISMATCH"
REJECTION_PURPOSE_MISMATCH = "PURPOSE_MISMATCH"
REJECTION_BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
REJECTION_CONSUMPTION_LIMIT_EXCEEDED = "CONSUMPTION_LIMIT_EXCEEDED"
REJECTION_ALREADY_APPLIED_ARTIFACT = "ALREADY_APPLIED_ARTIFACT"
REJECTION_DUPLICATE_RECEIPT = "DUPLICATE_RECEIPT"
REJECTION_STALE_LEDGER_HEAD = "STALE_LEDGER_HEAD"
REJECTION_CANONICAL_WRITE_ATTEMPT = "CANONICAL_WRITE_ATTEMPT"

ALL_REJECTION_CODES = [
    REJECTION_ARTIFACT_SCHEMA_INVALID,
    REJECTION_ARTIFACT_LIFECYCLE_NOT_UNAPPLIED,
    REJECTION_ARTIFACT_DIGEST_MISMATCH,
    REJECTION_COMPILER_IDENTITY_MISMATCH,
    REJECTION_CAPABILITY_IDENTITY_MISMATCH,
    REJECTION_EXPECTED_STATE_DIGEST_MISMATCH,
    REJECTION_LIFECYCLE_INELIGIBLE,
    REJECTION_CONSUMER_IDENTITY_MISMATCH,
    REJECTION_AUTHORITY_DOMAIN_VIOLATION,
    REJECTION_SCOPE_MISMATCH,
    REJECTION_PURPOSE_MISMATCH,
    REJECTION_BUDGET_EXCEEDED,
    REJECTION_CONSUMPTION_LIMIT_EXCEEDED,
    REJECTION_ALREADY_APPLIED_ARTIFACT,
    REJECTION_DUPLICATE_RECEIPT,
    REJECTION_STALE_LEDGER_HEAD,
    REJECTION_CANONICAL_WRITE_ATTEMPT,
]


def validate_lifecycle_transition(state: dict) -> tuple[str, list[str]]:
    """Check if the capability lifecycle allows application.

    Returns (outcome, reasons).
    """
    lifecycle = state.get("current_lifecycle_state", "UNAPPLIED")

    if lifecycle not in VALID_LIFECYCLE_STATES:
        return REJECTION_LIFECYCLE_INELIGIBLE, ["invalid_lifecycle_state"]

    # Must be in CONSUMED state to apply (GRANTED_UNCONSUMED is pre-consumption)
    if lifecycle == "APPLIED":
        return REJECTION_LIFECYCLE_INELIGIBLE, ["already_applied"]

    if lifecycle not in ("CONSUMED",):
        return REJECTION_LIFECYCLE_INELIGIBLE, [f"ineligible_state:{lifecycle}"]

    return APPLICATION_ACCEPTED, []


def validate_artifact_lifecycle(artifact: dict) -> tuple[str, list[str]]:
    """Check that the artifact is exactly UNAPPLIED.

    Returns (outcome, reasons).
    """
    app_state = artifact.get("application_state", "UNKNOWN")

    if app_state not in VALID_APPLICATION_STATES:
        return REJECTION_ARTIFACT_LIFECYCLE_NOT_UNAPPLIED, [f"invalid_application_state:{app_state}"]

    if app_state != "UNAPPLIED":
        return REJECTION_ALREADY_APPLIED_ARTIFACT, ["artifact_already_applied"]

    return APPLICATION_ACCEPTED, []
