"""Freeze continuity v2 byte vectors from the qualified Python implementation (PR #36, main bae6952).

One-shot offline tooling. Run against the tree where ``elpis.continuity.record`` is still the Python
implementation; the output file is then the frozen reference that the Rust authority must reproduce. The
generator is not used by any test and is removed together with the Python authority.

    PYTHONPATH=src python native/continuity/tests/fixtures/generate_v2_vectors.py > \
        native/continuity/tests/fixtures/continuity_v2_vectors.txt
"""
import hashlib
import struct

from elpis.continuity import record as R
from elpis.continuity.record import ContinuityError, ContinuitySnapshot, EvolutionAuthority

MAX = (1 << 63) - 1


def d(label: str) -> bytes:
    return hashlib.sha256(label.encode()).digest()


def h(label: str) -> str:
    return hashlib.sha256(label.encode()).hexdigest()


def body(magic=b"ELPCONT\x02", version=2, reserved=bytes(6), generation=1, cognition=0, pad=bytes(7), k1=bytes(32),
         revision=0, head=bytes(32), state=0, epad=bytes(7), pending=bytes(32)):
    return struct.pack(">8sH6sQB7s32sQ32sB7s32s", magic, version, reserved, generation, cognition, pad, k1,
                       revision, head, state, epad, pending)


def sealed(raw: bytes) -> bytes:
    return raw + hashlib.sha256(b"elpis.continuity.register.v2\x00" + raw).digest()


valid = {
    "genesis": ContinuitySnapshot(1, None, EvolutionAuthority(0, "0" * 64)),
    "anchored": ContinuitySnapshot(2, d("k1-0"), EvolutionAuthority(0, "0" * 64)),
    "pending_genesis": ContinuitySnapshot(3, d("k1-0"), EvolutionAuthority(0, "0" * 64, h("assertion-1"))),
    "idle_after_finalize": ContinuitySnapshot(4, d("k1-1"), EvolutionAuthority(1, h("receipt-1"))),
    "pending_unanchored": ContinuitySnapshot(7, None, EvolutionAuthority(5, h("receipt-5"), h("assertion-6"))),
    "pending_zero_assertion": ContinuitySnapshot(9, d("k1-9"), EvolutionAuthority(2, h("receipt-2"), "0" * 64)),
    "anchored_zero_k1": ContinuitySnapshot(5, bytes(32), EvolutionAuthority(0, "0" * 64)),
    "max_counters": ContinuitySnapshot(MAX, d("k1-max"), EvolutionAuthority(MAX, h("receipt-max"), h("assertion-max"))),
    "max_counters_idle": ContinuitySnapshot(MAX - 1, d("k1-max"), EvolutionAuthority(MAX - 1, h("receipt-max"))),
}

genesis_raw = R.encode_record(valid["genesis"])
flipped = bytearray(R.encode_record(valid["anchored"]))
flipped[40] ^= 0x01
invalid = {
    "empty_slot": bytes(R.RECORD_SIZE),
    "checksum_flipped_bit": bytes(flipped),
    "v1_magic_v2_size": sealed(body(magic=b"ELPCONT\x01")),
    "v1_version_field": sealed(body(version=1)),
    "v1_record_136": (lambda b1: b1 + hashlib.sha256(b"elpis.continuity.register.v1\x00" + b1).digest())(
        struct.pack(">8sH6sQB7s32sQ32s", b"ELPCONT\x01", 1, bytes(6), 1, 0, bytes(7), bytes(32), 0, bytes(32))),
    "short_175": genesis_raw[:-1],
    "long_177": genesis_raw + b"\x00",
    "reserved_header_nonzero": sealed(body(reserved=b"\x00\x00\x00\x00\x00\x01")),
    "cognition_pad_nonzero": sealed(body(pad=b"\x01" + bytes(6))),
    "cognition_state_2": sealed(body(cognition=2, k1=d("k1-0"))),
    "unanchored_nonzero_k1": sealed(body(cognition=0, k1=d("k1-0"))),
    "generation_zero": sealed(body(generation=0)),
    "generation_over_max": sealed(body(generation=MAX + 1)),
    "revision_over_max": sealed(body(revision=MAX + 1, head=d("receipt-x"))),
    "genesis_head_nonzero": sealed(body(revision=0, head=d("receipt-x"))),
    "revision_head_zero": sealed(body(revision=3, head=bytes(32))),
    "evolution_state_2": sealed(body(state=2, pending=d("assertion-1"))),
    "evolution_pad_nonzero": sealed(body(epad=b"\x01" + bytes(6))),
    "idle_nonzero_assertion": sealed(body(state=0, pending=d("assertion-1"))),
    "domain_v1_checksum": body() + hashlib.sha256(b"elpis.continuity.register.v1\x00" + body()).digest(),
}

print("# Continuity register v2 byte vectors, frozen from the qualified Python implementation at main bae6952")
print("# (PR #36). Generated by generate_v2_vectors.py in this directory; never regenerated by tests.")
print("# Fields: name expect generation anchored k1 revision head pending assertion evolution_digest record_digest record_hex")
print("# expect: ok (decodes to the fields shown), empty (all-zero slot), corrupt (refused). '-' marks an absent field.")
for name, snap in valid.items():
    raw = R.encode_record(snap)
    assert R.decode_record(raw) == snap and len(raw) == R.RECORD_SIZE
    ev = snap.evolution
    print(name, "ok", snap.generation, int(snap.anchored), (snap.k1_state_digest or bytes(32)).hex(), ev.revision,
          ev.head, int(ev.pending_assertion is not None), ev.pending_assertion or "0" * 64, ev.digest, snap.digest,
          raw.hex())
for name, raw in invalid.items():
    try:
        out = R.decode_record(raw)
    except ContinuityError as exc:
        assert exc.code == "CONTINUITY_CORRUPT", (name, exc.code)
        expect = "corrupt"
    else:
        assert out is None, name
        expect = "empty"
    print(name, expect, *(["-"] * 9), raw.hex())


def sequence(out_path):
    """The slot bytes after each operation of a fixed store session (both slots, in order)."""
    import tempfile
    from pathlib import Path
    from elpis.continuity import ContinuityStore, SLOT_NAMES

    lines = ["# Continuity v2 store session, frozen from the qualified Python implementation at main bae6952.",
             "# Fields: step op arg1 arg2 slot_a_hex slot_b_hex  (args are hex digests or '-').",
             "# Ops: open | anchor K1 | commit BEFORE AFTER | reserve ASSERTION | finalize RECEIPT | reopen"]
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "c"
        store = ContinuityStore(path).open()

        def dump(step, op, a="-", b="-"):
            slots = [(path / n).read_bytes().hex() for n in SLOT_NAMES]
            lines.append(" ".join([str(step), op, a, b, *slots]))

        dump(0, "open")
        k = [d(f"k1-{i}") for i in range(4)]
        store.anchor_cognition(k[0]); dump(1, "anchor", k[0].hex())
        store.commit_cognition_transition(k[0], k[1]); dump(2, "commit", k[0].hex(), k[1].hex())
        p = store.reserve_evolution_assertion(store.snapshot().evolution, h("assertion-1")).evolution
        dump(3, "reserve", h("assertion-1"))
        store.commit_cognition_transition(k[1], k[2]); dump(4, "commit", k[1].hex(), k[2].hex())
        store.commit_evolution_transition(store.snapshot().evolution, h("receipt-1")); dump(5, "finalize", h("receipt-1"))
        store.reserve_evolution_assertion(store.snapshot().evolution, h("assertion-2")); dump(6, "reserve", h("assertion-2"))
        store.close()
        store = ContinuityStore(path).open(); dump(7, "reopen")
        store.commit_evolution_transition(store.snapshot().evolution, h("receipt-2")); dump(8, "finalize", h("receipt-2"))
        store.commit_cognition_transition(k[2], k[3]); dump(9, "commit", k[2].hex(), k[3].hex())
        store.close()
    Path(out_path).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        sequence(sys.argv[1])
