# Shared native build policy for every Elpis subsystem.
#
# Every target that the default build produces must be created through
# elpis_add_library / elpis_add_test so that it is attributed to one live
# subsystem of ELPIS_SYSTEM.json. elpis_verify_targets() (called at the end of
# the root CMakeLists.txt) fails configuration if any default target is
# unattributed, if a library is not declared in the authority, or if a
# declared library is not built.

set(ELPIS_SYSTEM_JSON "${CMAKE_CURRENT_LIST_DIR}/../ELPIS_SYSTEM.json")
file(READ "${ELPIS_SYSTEM_JSON}" ELPIS_SYSTEM_TEXT)
set_property(GLOBAL PROPERTY ELPIS_REGISTERED_TARGETS "")

function(_elpis_live_subsystem subsystem out)
  string(JSON count LENGTH "${ELPIS_SYSTEM_TEXT}" subsystems)
  math(EXPR last "${count} - 1")
  set(found "")
  foreach(i RANGE ${last})
    string(JSON id GET "${ELPIS_SYSTEM_TEXT}" subsystems ${i} id)
    if(id STREQUAL subsystem)
      string(JSON status GET "${ELPIS_SYSTEM_TEXT}" subsystems ${i} status)
      if(status STREQUAL "PLANNED")
        message(FATAL_ERROR "native target for subsystem '${subsystem}' which is still PLANNED in ELPIS_SYSTEM.json")
      endif()
      set(found ${i})
    endif()
  endforeach()
  if(found STREQUAL "")
    message(FATAL_ERROR "native target attributed to undeclared subsystem '${subsystem}'")
  endif()
  set(${out} ${found} PARENT_SCOPE)
endfunction()

function(elpis_warnings target)
  if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(ELPIS_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()

function(_elpis_register subsystem target kind)
  _elpis_live_subsystem(${subsystem} _index)
  set_property(GLOBAL APPEND PROPERTY ELPIS_REGISTERED_TARGETS "${target}")
  set_target_properties(${target} PROPERTIES ELPIS_SUBSYSTEM "${subsystem}" ELPIS_KIND "${kind}")
  elpis_warnings(${target})
  if(kind STREQUAL "test")
    # Tests assert with assert(): they must check in every build type,
    # including Release, where NDEBUG would silently turn them into no-ops.
    target_compile_options(${target} PRIVATE -UNDEBUG)
  endif()
endfunction()

# elpis_add_library(<subsystem> <name> STATIC|SHARED <sources...>)
function(elpis_add_library subsystem name kind)
  add_library(${name} ${kind} ${ARGN})
  _elpis_register(${subsystem} ${name} library)
endfunction()

# elpis_add_test_library(<subsystem> <name> <sources...>): test-only support code.
function(elpis_add_test_library subsystem name)
  add_library(${name} STATIC ${ARGN})
  _elpis_register(${subsystem} ${name} test)
endfunction()

# elpis_add_test(<subsystem> <name> SOURCES <src...> [LIBS <libs...>] [ARGS <args...>]
#                [INCLUDES <dirs...>] [TIMEOUT <s>])
function(elpis_add_test subsystem name)
  cmake_parse_arguments(T "" "TIMEOUT" "SOURCES;LIBS;ARGS;INCLUDES;DEFINES" ${ARGN})
  add_executable(${name} ${T_SOURCES})
  if(T_LIBS)
    target_link_libraries(${name} PRIVATE ${T_LIBS})
  endif()
  if(T_INCLUDES)
    target_include_directories(${name} PRIVATE ${T_INCLUDES})
  endif()
  if(T_DEFINES)
    target_compile_definitions(${name} PRIVATE ${T_DEFINES})
  endif()
  _elpis_register(${subsystem} ${name} test)
  add_test(NAME ${subsystem}.${name} COMMAND ${name} ${T_ARGS})
  set_tests_properties(${subsystem}.${name} PROPERTIES LABELS "${subsystem}")
  if(T_TIMEOUT)
    set_tests_properties(${subsystem}.${name} PROPERTIES TIMEOUT ${T_TIMEOUT})
  endif()
endfunction()

function(_elpis_collect_targets dir out)
  get_property(targets DIRECTORY "${dir}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(subdirs DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
  foreach(sub IN LISTS subdirs)
    _elpis_collect_targets("${sub}" nested)
    list(APPEND targets ${nested})
  endforeach()
  set(${out} ${targets} PARENT_SCOPE)
endfunction()

function(elpis_verify_targets)
  _elpis_collect_targets("${CMAKE_SOURCE_DIR}" all_targets)
  get_property(registered GLOBAL PROPERTY ELPIS_REGISTERED_TARGETS)
  set(manifest "{\n  \"schema\": \"elpis.native-targets.v1\",\n  \"targets\": [")
  set(sep "")
  foreach(target IN LISTS all_targets)
    list(FIND registered "${target}" at)
    if(at EQUAL -1)
      message(FATAL_ERROR "native target '${target}' is not attributed to a subsystem; use elpis_add_library/elpis_add_test")
    endif()
    get_target_property(subsystem ${target} ELPIS_SUBSYSTEM)
    get_target_property(kind ${target} ELPIS_KIND)
    string(APPEND manifest "${sep}\n    {\"name\": \"${target}\", \"subsystem\": \"${subsystem}\", \"kind\": \"${kind}\"}")
    set(sep ",")
    if(kind STREQUAL "library")
      _elpis_live_subsystem(${subsystem} i)
      string(JSON declared GET "${ELPIS_SYSTEM_TEXT}" subsystems ${i} native_targets)
      string(JSON n LENGTH "${declared}")
      set(ok FALSE)
      if(n GREATER 0)
        math(EXPR last "${n} - 1")
        foreach(j RANGE ${last})
          string(JSON candidate GET "${declared}" ${j})
          if(candidate STREQUAL target)
            set(ok TRUE)
          endif()
        endforeach()
      endif()
      if(NOT ok)
        message(FATAL_ERROR "native library '${target}' is not declared in ELPIS_SYSTEM.json subsystem '${subsystem}'")
      endif()
    endif()
  endforeach()
  # Every declared native library must actually be built.
  string(JSON count LENGTH "${ELPIS_SYSTEM_TEXT}" subsystems)
  math(EXPR last "${count} - 1")
  foreach(i RANGE ${last})
    string(JSON declared GET "${ELPIS_SYSTEM_TEXT}" subsystems ${i} native_targets)
    string(JSON n LENGTH "${declared}")
    if(n GREATER 0)
      math(EXPR lastj "${n} - 1")
      foreach(j RANGE ${lastj})
        string(JSON candidate GET "${declared}" ${j})
        if(NOT TARGET ${candidate})
          message(FATAL_ERROR "ELPIS_SYSTEM.json declares native library '${candidate}' that the build does not produce")
        endif()
      endforeach()
    endif()
  endforeach()
  string(APPEND manifest "\n  ]\n}\n")
  file(WRITE "${CMAKE_BINARY_DIR}/elpis_native_targets.json" "${manifest}")
endfunction()
